POST http://localhost/api/youtube_channel/store
Accept: text/json
Authorization: Bearer edpklfKb1hEYaU7ibsFZlfJtOE70JozxW0oF1QEfwkNU1wb0NiptFSieLMk0
Content-Type: application/json

{
    "yc_name":"1111111",
    "yc_id":"2222222222"
}
